### ISSUE TITLE
Cut hierarchy at a given height

### ISSUE THREAD

**Issue by rajarshi** [lbehnke/hierarchical-clustering-java#13]
It would be nice to be able to take a clustering and "cut" it at a given height and identify the N clusters and the row ids (of the original distance matrix) in those N clusters. For example, on the front page of the repo, the top figure shows a dendrogram. if it were cut at at say 3, we'd get 4 clusters: (06) (03 05) (04) (01 02)

Is it possible to do this using the current methods of Cluster? If not, would it be possible to add such functionality?

**Comment by emanlee** [comment]
Here is a figure on this home page: https://github.com/lbehnke/hierarchical-clustering-java.  From this dendrogram, how can we get clusters or groups. For example, if we want get two clusters, it should be [o6] [o1 o2 o3 o4 o5]; If we want get three clusters, it should be [06] [03 05] [01 02 04 ]. How to use codes to get such clusters and output them to console or files? Thanks!

**Comment by emanlee** [comment]
In my case, I have more than 800 samples/genes. After clustering, the dendrogram is very big and complex, therfore, we need to divide/cut/sect the dendrogram into clusters and save them to files (each file contains the gene names and represents a cluster/group).
