### ISSUE TITLE
Add Newick exporter

### ISSUE THREAD

**Issue by lbehnke** [lbehnke/hierarchical-clustering-java#15]
See https://github.com/jasondavies/newick.js/blob/master/src/newick.js

**Comment by otorreno** [comment]
I think this issue should be closed as #23 has been merged already. Is there any chance to release a new version to maven? the current one (1.1.0) is from February 2015. Thanks in advance

**Comment by lbehnke** [comment]
I have just release v1.2 and pushed the lib to maven central.

**Comment by otorreno** [comment]
thanks @lbehnke! I updated the package version and I am no able to obtain the newick representation
