### ISSUE TITLE
Problems in multi-thread

### ISSUE THREAD

**Issue by csushin** [lbehnke/hierarchical-clustering-java#17]
Hi, first of all, sincerely appreciate your code.
I am trying to use this code in multi-thread. More specifically, i have multiple image and call your hierarchical clustering algorithm on every pixel on the same time. And it will give me the error that:
![image](https://cloud.githubusercontent.com/assets/3353795/12667432/97e21e2a-c608-11e5-8057-09595ae3bd85.png)
M___*\* represents the name of the leaf node. clstr#**\* represents the automatically generated cluster name. 

This error will only show occasionally in some thread which will cause the exceptions. And this error won't show up if i do not use multi-thread. Do you have any idea on this? If you need more information, just let me know.

Thanks!

**Comment by lbehnke** [comment]
Sorry for not coming back to this earlier.
I'd recommend building first a distance matrix from the images, which is then passed to the `DefaultClusteringAlgorithm` *OR* use a `DefaultClusteringAlgorithm` instance per thread.
