### ISSUE TITLE
names duplicate

### ISSUE THREAD

**Issue by tyrcho** [lbehnke/hierarchical-clustering-java#7]
The error shown when you perform clustering with an array of non unique names is pretty tough to track ...

I suggest to add a check for uniqueness on the arguments [here](https://github.com/lbehnke/hierarchical-clustering-java/blob/master/src/main/java/com/apporiented/algorithm/clustering/DefaultClusteringAlgorithm.java#L38) using for instance a new Hashset initialized with the names and compare the size of the hashset with the size of the names array.

**Comment by lbehnke** [comment]
Sounds good. Could you send a pull request?

**Comment by tyrcho** [comment]
OK, I'll try to have a look at it next week.
